### ISSUE TITLE
Chester Theme

### ISSUE THREAD

**Issue by henrikdahl** [ynnoj/hyperterm-chester#1]
Noticed the chester name was occupied.

Just finished and released a [Chesterish](https://github.com/henrikdahl/hyperterm-chesterish) theme that might fit your needs. ✌️

Please disregard this if not and good luck with your theme 👊

**Comment by ynnoj** [comment]
@henrikdahl Nice!

I'm going to be using a slightly different palette from an [Atom theme](https://github.com/csutter/chester-atom-syntax) with the same name.

Awesome contribution to the HyperTerm community though 🤘
